create table if not exists public.erp_page_definitions(
  id bigint generated by default as identity primary key,
  page_key text unique not null,
  page_name text not null,
  page_group text default 'Other',
  page_type text default 'standard',
  page_url text,
  page_description text,
  menu_label text,
  protected boolean default false,
  active boolean default true,
  updated_at timestamptz default now()
);

create table if not exists public.erp_page_versions(
  id bigint generated by default as identity primary key,
  page_key text not null,
  version_no integer not null,
  config_json jsonb not null default '{}'::jsonb,
  is_published boolean default false,
  created_by text,
  created_at timestamptz default now(),
  published_by text,
  published_at timestamptz,
  unique(page_key,version_no)
);

insert into public.erp_page_definitions(page_key,page_name,page_group,page_type,page_url,page_description,menu_label,protected)
values
('dashboard','Dashboard','Core','dashboard','index.html','Main ERP dashboard','Dashboard',true),
('masters','Master Framework','Masters','standard','masters.html','Item, supplier, workshop and department masters','Masters',true),
('master_center','Other Masters Center','Masters','standard','master-center.html','Unit, category, carrier, authority, employee, vehicle and location masters','Other Masters Center',true),
('rack_management','Rack Management','Inventory','transaction','rack-management.html','Rack setup, item allocation and rack transfers','Rack Management',true),
('inventory_intelligence','Inventory Intelligence','Inventory','dashboard','inventory-intelligence.html','Stock value and movement intelligence','Inventory Intelligence',true),
('erp_core_settings','ERP Core Settings','ERP Core','settings','erp-core-settings.html','ERP numbering and inventory rules','ERP Core Settings',true),
('erp_relationship_center','ERP Relationship Center','ERP Core','settings','erp-relationship-center.html','Master-data relationships and autofill','ERP Relationship Center',true),
('erp_health_center','ERP Data Health Center','ERP Core','dashboard','erp-health-center.html','ERP health and data quality checks','ERP Data Health Center',true),
('erp_health_control_tower','ERP Health Control Tower','ERP Core','dashboard','erp-health-control-tower.html','Executive ERP health control tower','ERP Health Control Tower',true),
('local_purchase','Local Purchase','Purchases','transaction','purchase-entry.html?type=local','Local purchase entry','Local Purchase',true),
('zafar_purchase','Zafar Purchase','Purchases','transaction','purchase-entry.html?type=zafar','Zafar purchase entry','Zafar Purchase',true),
('board_purchase','Board Purchase','Purchases','transaction','purchase-entry.html?type=board','Board purchase entry','Board Purchase',true),
('purchase_list','Purchase List','Purchases','report','purchase-list.html','Purchase search, detail and reporting','Purchase List',true),
('issue_entry','Issue Entry','Inventory','transaction','issue-entry.html','Inventory issue entry','Issue Entry',true),
('rgp_entry','RGP Entry','Gate Pass','transaction','rgp-entry.html','Returnable gate pass entry','RGP Entry',true),
('rgp_list','RGP List','Gate Pass','report','rgp-list.html','Returnable gate pass records','RGP List',true),
('ogp_entry','OGP Entry','Gate Pass','transaction','ogp-entry.html','Outward gate pass entry','OGP Entry',true),
('ogp_list','OGP List','Gate Pass','report','ogp-list.html','Outward gate pass records','OGP List',true)
on conflict(page_key) do nothing;

alter table public.erp_page_definitions enable row level security;
alter table public.erp_page_versions enable row level security;

drop policy if exists "Public all erp_page_definitions" on public.erp_page_definitions;
create policy "Public all erp_page_definitions" on public.erp_page_definitions for all using(true) with check(true);

drop policy if exists "Public all erp_page_versions" on public.erp_page_versions;
create policy "Public all erp_page_versions" on public.erp_page_versions for all using(true) with check(true);
