create table if not exists public.erp_health_snapshots(
id bigint generated by default as identity primary key,
overall_score numeric,passed_checks integer,warning_checks integer,error_checks integer,
result_data jsonb,created_at timestamptz default now());
alter table public.erp_health_snapshots enable row level security;
drop policy if exists "Public all erp_health_snapshots" on public.erp_health_snapshots;
create policy "Public all erp_health_snapshots" on public.erp_health_snapshots for all using(true) with check(true);