create table if not exists public.erp_relationships(
  id bigint generated by default as identity primary key,
  relation_type text not null,
  source_table text not null,
  source_id text not null,
  target_table text not null,
  target_id text not null,
  relation_data jsonb default '{}'::jsonb,
  active boolean default true,
  updated_at timestamptz default now(),
  unique(relation_type,source_table,source_id,target_table,target_id)
);

alter table public.erp_relationships enable row level security;

drop policy if exists "Public all erp_relationships" on public.erp_relationships;
create policy "Public all erp_relationships"
on public.erp_relationships
for all
using(true)
with check(true);
