create table if not exists public.erp_design_studio_preferences(
  id bigint generated by default as identity primary key,
  user_name text not null,
  preference_key text not null,
  preference_value jsonb default '{}'::jsonb,
  updated_at timestamptz default now(),
  unique(user_name,preference_key)
);

alter table public.erp_design_studio_preferences enable row level security;

drop policy if exists "Public all erp_design_studio_preferences"
on public.erp_design_studio_preferences;

create policy "Public all erp_design_studio_preferences"
on public.erp_design_studio_preferences
for all
using(true)
with check(true);
