create table if not exists public.erp_component_templates(
  id bigint generated by default as identity primary key,
  component_key text unique not null,
  component_name text not null,
  component_category text,
  component_config jsonb default '{}'::jsonb,
  active boolean default true,
  created_at timestamptz default now()
);

alter table public.erp_component_templates enable row level security;

drop policy if exists "Public all erp_component_templates" on public.erp_component_templates;
create policy "Public all erp_component_templates"
on public.erp_component_templates
for all
using(true)
with check(true);
