create table if not exists public.erp_health_ignored(
id bigint generated by default as identity primary key,
check_id text unique not null,note text,ignored_at timestamptz default now());
create table if not exists public.erp_health_repairs(
id bigint generated by default as identity primary key,
check_id text,action text not null,affected_records integer default 0,
details jsonb default '{}'::jsonb,repaired_at timestamptz default now());
alter table public.erp_health_ignored enable row level security;
alter table public.erp_health_repairs enable row level security;
drop policy if exists "Public all erp_health_ignored" on public.erp_health_ignored;
create policy "Public all erp_health_ignored" on public.erp_health_ignored for all using(true) with check(true);
drop policy if exists "Public all erp_health_repairs" on public.erp_health_repairs;
create policy "Public all erp_health_repairs" on public.erp_health_repairs for all using(true) with check(true);
