create table if not exists public.erp_settings(
  id bigint generated by default as identity primary key,
  setting_key text unique not null,
  setting_value text,
  setting_group text default 'general',
  updated_at timestamptz default now()
);

create table if not exists public.erp_number_sequences(
  id bigint generated by default as identity primary key,
  sequence_type text unique not null,
  prefix text not null,
  last_number bigint default 0,
  padding integer default 5,
  suffix text default '',
  active boolean default true,
  updated_at timestamptz default now()
);

create table if not exists public.audit_log(
  id bigint generated by default as identity primary key,
  action text not null,
  module text,
  record_type text,
  record_id text,
  old_data jsonb,
  new_data jsonb,
  user_name text,
  created_at timestamptz default now()
);

insert into public.erp_number_sequences(sequence_type,prefix,last_number,padding,suffix)
values
('ITEM','ITM-',0,5,''),
('SUPPLIER','SUP-',0,5,''),
('DEPARTMENT','DEP-',0,5,''),
('WORKSHOP','WSP-',0,5,''),
('PURCHASE','PUR-',0,5,''),
('ISSUE','ISS-',0,5,''),
('RGP','RGP-',0,5,''),
('OGP','OGP-',0,5,''),
('IGP','IGP-',0,5,''),
('GRN','GRN-',0,5,'')
on conflict(sequence_type) do nothing;

create or replace function public.next_erp_number(p_type text)
returns text
language plpgsql
security definer
as $$
declare
  seq public.erp_number_sequences%rowtype;
  result text;
begin
  select * into seq from public.erp_number_sequences
  where sequence_type=upper(p_type) and active=true
  for update;

  if not found then
    raise exception 'Number sequence not found for %',p_type;
  end if;

  update public.erp_number_sequences
  set last_number=last_number+1,updated_at=now()
  where id=seq.id
  returning * into seq;

  result:=seq.prefix||lpad(seq.last_number::text,seq.padding,'0')||coalesce(seq.suffix,'');
  return result;
end $$;

alter table public.erp_settings enable row level security;
alter table public.erp_number_sequences enable row level security;
alter table public.audit_log enable row level security;

drop policy if exists "Public all erp_settings" on public.erp_settings;
create policy "Public all erp_settings" on public.erp_settings for all using(true) with check(true);

drop policy if exists "Public all erp_number_sequences" on public.erp_number_sequences;
create policy "Public all erp_number_sequences" on public.erp_number_sequences for all using(true) with check(true);

drop policy if exists "Public all audit_log" on public.audit_log;
create policy "Public all audit_log" on public.audit_log for all using(true) with check(true);

grant execute on function public.next_erp_number(text) to anon,authenticated;
