create table if not exists public.erp_theme_settings(
  id bigint generated by default as identity primary key,
  setting_key text unique not null,
  theme_json jsonb not null default '{}'::jsonb,
  updated_by text,
  updated_at timestamptz default now()
);

alter table public.erp_theme_settings enable row level security;

drop policy if exists "Public all erp_theme_settings" on public.erp_theme_settings;
create policy "Public all erp_theme_settings"
on public.erp_theme_settings
for all
using(true)
with check(true);

insert into public.erp_theme_settings(setting_key,theme_json,updated_by)
values(
  'global',
  '{
    "name":"Eye Comfort Navy",
    "pageBackground":"#f8fafc",
    "workspaceBackground":"#eef3f8",
    "cardBackground":"#ffffff",
    "primaryText":"#0f172a",
    "mutedText":"#64748b",
    "borderColor":"#dbe3ee",
    "primaryColor":"#2563eb",
    "secondaryColor":"#f59e0b",
    "successColor":"#16a34a",
    "warningColor":"#f97316",
    "dangerColor":"#dc2626",
    "infoColor":"#2563eb",
    "sidebarBackground":"#111827",
    "sidebarText":"#ffffff",
    "activeBackground":"#f59e0b",
    "activeText":"#111827",
    "hoverBackground":"#1e293b",
    "tableHeaderBackground":"#f59e0b",
    "tableHeaderText":"#111827",
    "tableRowHover":"#f8fafc",
    "cardRadius":12,
    "buttonRadius":8,
    "inputRadius":8,
    "shadowStrength":"soft",
    "fontFamily":"Inter, Arial, sans-serif",
    "baseFontSize":14,
    "density":"comfortable"
  }'::jsonb,
  'Muhammad Waqas'
)
on conflict(setting_key) do nothing;
