create table if not exists public.erp_shell_settings(
  id bigint generated by default as identity primary key,
  setting_key text unique not null,
  settings_json jsonb not null default '{}'::jsonb,
  updated_by text,
  updated_at timestamptz default now()
);

alter table public.erp_shell_settings enable row level security;

drop policy if exists "Public all erp_shell_settings" on public.erp_shell_settings;
create policy "Public all erp_shell_settings"
on public.erp_shell_settings
for all
using(true)
with check(true);

insert into public.erp_shell_settings(setting_key,settings_json,updated_by)
values(
  'global',
  '{
    "navigationPosition":"top",
    "startupPage":"erp-design-studio.html",
    "profileVisible":true,
    "profilePosition":"top-left",
    "profileName":"Muhammad Waqas",
    "profileDesignation":"Store Officer",
    "profileStatusText":"Online"
  }'::jsonb,
  'Muhammad Waqas'
)
on conflict(setting_key) do nothing;
