create table if not exists public.erp_shell_settings(
  id bigint generated by default as identity primary key,
  setting_key text unique not null,
  settings_json jsonb not null default '{}'::jsonb,
  updated_by text,
  updated_at timestamptz default now()
);

alter table public.erp_shell_settings enable row level security;

drop policy if exists "Public all erp_shell_settings" on public.erp_shell_settings;
create policy "Public all erp_shell_settings"
on public.erp_shell_settings for all using(true) with check(true);

insert into public.erp_shell_settings(setting_key,settings_json,updated_by,updated_at)
values(
  'global',
  '{
    "navigationPosition":"left",
    "startupPage":"index.html",
    "sidebarWidth":170,
    "sidebarDefaultCollapsed":false,
    "profileVisible":true,
    "profilePosition":"left-bottom",
    "profileLayout":"vertical",
    "profileName":"Muhammad Waqas",
    "profileDesignation":"Store Officer",
    "profileStatusText":"Online",
    "profileImage":"public/waqas.jpg.png",
    "topBarBackground":"#0f172a",
    "topBarTextColor":"#ffffff",
    "activeColor":"#f59e0b"
  }'::jsonb,
  'Muhammad Waqas',
  now()
)
on conflict(setting_key) do update
set settings_json=excluded.settings_json,
    updated_by=excluded.updated_by,
    updated_at=excluded.updated_at;
