-- MASTER CENTER TABLES
-- Run this once in Supabase SQL Editor.

create table if not exists public.units (
  id bigint generated by default as identity primary key,
  unit_code text unique not null,
  unit_name text unique not null,
  short_name text not null,
  decimal_allowed text default 'Yes',
  decimal_places integer default 2,
  status text default 'Active',
  remarks text,
  created_at timestamptz default now()
);

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  category_code text unique not null,
  category_name text unique not null,
  inventory_type text default 'Inventory',
  parent_category text,
  reorder_policy text default 'Normal',
  status text default 'Active',
  remarks text,
  created_at timestamptz default now()
);

create table if not exists public.carriers (
  id bigint generated by default as identity primary key,
  carrier_code text unique not null,
  carrier_name text unique not null,
  father_name text,
  mobile_no text,
  cnic text,
  vehicle_no text,
  address text,
  status text default 'Active',
  remarks text,
  created_at timestamptz default now()
);

create table if not exists public.authorized_persons (
  id bigint generated by default as identity primary key,
  authority_code text unique not null,
  employee_id text,
  person_name text unique not null,
  designation text,
  department text,
  approval_level text default 'Level 1',
  mobile_no text,
  can_authorize_rgp text default 'Yes',
  can_authorize_ogp text default 'Yes',
  status text default 'Active',
  remarks text,
  created_at timestamptz default now()
);

create table if not exists public.employees (
  id bigint generated by default as identity primary key,
  employee_code text unique not null,
  employee_id text unique not null,
  employee_name text not null,
  father_name text,
  designation text,
  department text,
  mobile_no text,
  email text,
  cnic text,
  joining_date date,
  employment_type text default 'Permanent',
  status text default 'Active',
  address text,
  remarks text,
  created_at timestamptz default now()
);

create table if not exists public.vehicles (
  id bigint generated by default as identity primary key,
  vehicle_code text unique not null,
  vehicle_no text unique not null,
  vehicle_type text,
  ownership text,
  driver_name text,
  driver_mobile text,
  company_name text,
  registration_expiry date,
  status text default 'Active',
  remarks text,
  created_at timestamptz default now()
);

create table if not exists public.store_locations (
  id bigint generated by default as identity primary key,
  location_code text unique not null,
  store_name text not null,
  zone text,
  rack_no text not null,
  shelf_no text not null,
  bin_no text,
  location_name text unique not null,
  capacity numeric,
  capacity_unit text,
  status text default 'Active',
  remarks text,
  created_at timestamptz default now()
);

alter table public.units enable row level security;
alter table public.categories enable row level security;
alter table public.carriers enable row level security;
alter table public.authorized_persons enable row level security;
alter table public.employees enable row level security;
alter table public.vehicles enable row level security;
alter table public.store_locations enable row level security;

do $$
declare t text;
begin
  foreach t in array array['units','categories','carriers','authorized_persons','employees','vehicles','store_locations']
  loop
    execute format('drop policy if exists "Public read %1$s" on public.%1$I',t);
    execute format('drop policy if exists "Public insert %1$s" on public.%1$I',t);
    execute format('drop policy if exists "Public update %1$s" on public.%1$I',t);
    execute format('drop policy if exists "Public delete %1$s" on public.%1$I',t);

    execute format('create policy "Public read %1$s" on public.%1$I for select using (true)',t);
    execute format('create policy "Public insert %1$s" on public.%1$I for insert with check (true)',t);
    execute format('create policy "Public update %1$s" on public.%1$I for update using (true) with check (true)',t);
    execute format('create policy "Public delete %1$s" on public.%1$I for delete using (true)',t);
  end loop;
end $$;
